### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by carlosg-czbiohub** [nvelden/NGLVieweR#12]
Hi,
Thanks for providing this package, it works great!

I just wanted to see if it would be possible to add something to 'remove' a viewer instance. I have the package running as part of a Shiny app that:

1. Takes in user data table (proteomics), 
2. Grabs a Uniprot ID from table and populates a dropdown with all the unique uniprot IDs
3. Queries a database to get a vector of PDB models associated with that Uniprot ID selected by user
4. Populates a dropdown based on those PDB IDs to generate the model using your package, along with some other representations.

Largely this works fine. However, I have detected that there are instances when a user selects a protein and the model loads correctly, but when the user selects a _new_ protein and the models available are (from what I can see) empty, the package **reloads** the previous model that was working and overlays the data for the newly selected protein, which is incorrect until the user selects a non-empty model. Here is the server code.

    output$proteinViewer <- renderNGLVieweR({
    req(input$modelSelection, peptideData(), input$groupSelection)

    # Get group-peptide coverage
    df <- peptideData()
    coverage_string <- prot_coverage(df = df, selectedProt = input$selectedProtein, expGroup = input$groupSelection)
    print(paste("Fetching model", input$modelSelection, "for group", input$groupSelection))

    # Visualize in NGLVieweR using the selected PDB model
    NGLVieweR(data = input$modelSelection) %>%
      stageParameters(backgroundColor = "white", zoomSpeed = 1) %>%
      addRepresentation("ribbon", param = list(name = "main", color = "skyblue")) %>%
      addRepresentation("ribbon", param = list(name = "coverage", sele = coverage_string, color = "green"))})

 Some of this cant be helped due to the lack of information I can get from API about model prior to rendering, but Ideally when this happens it would be nice to have a method to tie to a actionButton that could 'clear' the current model till a new one is selected.

**Comment by nvelden** [comment]
Could you maybe solve your issue by removing  the"main" and "coverage" representations using `NGLVieweR_proxy` and  `removeSelection` tied to an action button like done in the below example?

https://nvelden.github.io/NGLVieweR/articles/NGLVieweR.html#api

**Comment by carlosg-czbiohub** [comment]
Hi thanks so much for suggestion. I had tried that earlier and it had not worked to clear the image, but i tried it again and it seems to work!
