### ISSUE TITLE
Methods for overlaying or superimposing structures.

### ISSUE THREAD

**Issue by lee-t** [nvelden/NGLVieweR#15]
Not sure why #14 was closed, I dont see an answer nor do I see any newer features on multiple structures in the same view. So I'm suggesting a similar feature but I apologize if this has already been implemented and I missed it in the docs; I know its in the python and JS libraries but probably not yet implemented in this one. 

In the NGLView [ example gallery ](https://nglviewer.org/ngl/gallery/index.html)there are a few examples for loading 2 models and [aligning ](https://codepen.io/pen?&editors=001&layout=left)or [superpose ](https://codepen.io/pen?&editors=001&layout=left)them presumably based on structural alignment. 

An alternative would be to implement multiple structures in the same view and then add or manipulate the structures in R using some other protein library such as [bio3d](http://thegrantlab.org/bio3d/)

**Comment by nvelden** [comment]
I think this would be a very nice addition to the package but it would require major changes to the way the structures are loaded currently. I will give it a try but it will certainly take a view weeks to implement.

**Comment by bioboot** [comment]
I would also love this feature - to step back to #14 briefly: is it currently not possible to load multiple structures into the same viewer? Thanks!

**Comment by nvelden** [comment]
I’m currently working on a solution and have added a new function called addStructure in the `add-structures` branch. This function is still in the experimental stage, so I haven’t merged it into the main branch yet.

Here's an example of how addStructure can be used:

```
NGLVieweR("1CRN") %>%
  addRepresentation("cartoon", param = list(color = "blue")) %>%
  addStructure("1CRN") %>%
  addRepresentation("cartoon", param = list(color = "orange")) %>%
  setPosition(x = 20, y = 0, z = 0) %>%
  setRotation(x = 2, y = 0, z = 0, degrees = FALSE) %>% 
  setScale(0.5)
```

If you have any feedback on this implementation, I’d be glad to hear it.

**Comment by bioboot** [comment]
This works great. Thank you for this. 

I wonder is there a way, after adding a new_structure with `addStructure()`, to call `addRepresentation()` for a previous structure? I see the `NGLVieweR$x$structures` object but I don't yet know how to work with it effectively to change things after I create it. 

My use case here would be to apply a representation across all structures such as cartoon colored by structure (just as you have in your example) and then, afterwards, add licorice for some common amino acids of the different (including previous) structures. 

I guess I am asking: once you call `addStructure()` are you done with being able to manipulate the previous one or can you specify the model/structure number somehow?

Thanks again - I am loving the package by the way!

**Comment by nvelden** [comment]
@bioboot As it works now manipulating structures will work in order. I like the idea of adding a parameter where you can select the structure to update but it is not so easy to implement. I did add a `structureIndex` parameter to the `addSelection` function which is called after rendering as part of the API calls in Shiny applications.

**Comment by nvelden** [comment]
I also added a `setSuperpose` function which allows you to align structures based on selections

```
NGLVieweR("1GZM") %>%
   addRepresentation("cartoon", param = list(color = "blue")) %>%
   addStructure("1U19") %>%
   addRepresentation("cartoon", param = list(color = "orange")) %>%
   setSuperpose(
     reference = 1, 
     sele_reference = ":A", 
     sele_target = ":A", 
     superpose = TRUE
     )
```
![Screenshot 2024-11-15 at 15 00 52](https://github.com/user-attachments/assets/5f75f82e-8e43-4556-a912-8d13be66cbbe)
