### ISSUE TITLE
server site NGLVieweR_proxy function?

### ISSUE THREAD

**Issue by ChristianRohde** [nvelden/NGLVieweR#4]
Hi,

I used NGLVieweR a lot during the last days to build a shiny for our structure of interest and allow to easily select modification sites from a dropdown. This works pretty well thanks to your software. 

I used the recommended commands to add and change data and finally refresh the picture. Overall this relies on NGLVieweR_proxy and it works amazing if I work locally. Using the App from a Rstudio-Server via VPN or even worse via Shiny-Server (VPN and local Browser) does not work: unfortunately you need a rather good internet connection to up/download data. But I can confirm that it works again very well if I login via remote to a PC in the same local network. 

My question is: can I change the way NGLVieweR exchanges data? Is there something like a server site update function available similar to https://shiny.rstudio.com/articles/selectize.html? 

Best,
Christian

**Comment by nvelden** [comment]
Hi Christian,

I am afraid there is no other way to exchange data with the server. Did you have a look at: https://niels-van-der-velden.shinyapps.io/shinyNGLVieweR/ and the underlying code at https://github.com/nvelden/shinyNGLVieweR? The viewer runs on the most basic [shinyapps.io](https://www.shinyapps.io/) server and runs very smooth for me. I have a fast internet connection though...

One tip to make things faster is to limit surface representations as they are the most time consuming to calculate. Also, always remove the selection that you want to update first. If you do not do this you build up new selections every time you try to update which will make things rather slow over time.

```
 observeEvent(input$add, {

    #Remove selection named "sel1"  
   
    NGLVieweR_proxy("structure") %>%
      removeSelection("sel1")   

    # Add new selection with the same name

    NGLVieweR_proxy("structure") %>%
      addSelection(isolate(input$type),
                   param =
                     list(
                       name = "sel1", 
                       sele = isolate(input$selection),
                       colorValue = isolate(input$color)
                     )
      )
  })
```

**Comment by ChristianRohde** [comment]
Ok, thank you, but I am not sure if this helps. I work with a pdb from a complex with about 70 proteins and several RNA molecules. At the beginning I initialize each molecules with addRepresentation providing each a name and sele = "none". I tried, but it is not possible to combine NGLVieweR_proxy with addRepresentation later on. If selected in Shiny I make a NGLVieweR_proxy statment with updateSelection. In case of the proteins or RNA I use this to switch them on/off. For highlighting positions in the RNA I made duplicates and also do a updateSelection. This sounds a bit nasty but works quite nice and seems to be the only way how I can dissect the picture into useful parts on demand.

**Comment by nvelden** [comment]
In a `NGLVieweR_proxy` call you need to use `addSelection()` rather then `addRepresentation()` like I did in the example above. If you combine this with `removeSelection()` it is not necessary to make `addRepresentations()` with selection "none" when you initialize the molecule. 

If you work with very large PDBs consisting of multiple molecules the NGL selection language which makes it possible to select specific residues might be very helpful:

![image](https://user-images.githubusercontent.com/45127542/144992625-8f4ba057-ba81-4f99-aceb-3898350dc25a.png)
https://nglviewer.org/ngl/api/manual/usage/selection-language.html
