### ISSUE TITLE
Is there any way to display a grid view?

### ISSUE THREAD

**Issue by cwbcm** [nvelden/NGLVieweR#7]
Hi,

I wonder if there is a way to show molecules as grid view (pymol grid mode)? I would like to color the same protein with different metrics and show them side by side. When I rotate or zoom on one panel, the other ones rotate at the same time. Something like this:
![b0140](https://user-images.githubusercontent.com/57413825/183551978-a26c7c68-02ff-4f27-9144-ad2741f9f92a.png)

Thanks,
Chen

**Comment by nvelden** [comment]
Unfortunately, I don't see an easy way to link the different viewers such that they rotate or zoom at the same time. You can however lay multiple viewers in a grid quite easily:

```
library(shiny)
library(NGLVieweR)

ui <- fluidPage(
  div(style="display: flex;"
  NGLVieweROutput("structure1"),
  NGLVieweROutput("structure2"),
  NGLVieweROutput("structure3"),
  NGLVieweROutput("structure4")
  )

server <- function(input, output) {
  output$structure1 <- renderNGLVieweR({
    NGLVieweR("7CID") %>%
      addRepresentation("cartoon") %>%
      stageParameters(backgroundColor = "white")
  })
  output$structure2 <- renderNGLVieweR({
    NGLVieweR("7CID") %>%
      addRepresentation("ball+stick") %>%
      stageParameters(backgroundColor = "white")
  })
  output$structure3 <- renderNGLVieweR({
    NGLVieweR("7CID") %>%
      addRepresentation("backbone") %>%
      stageParameters(backgroundColor = "white")
  })
  output$structure4 <- renderNGLVieweR({
    NGLVieweR("7CID") %>%
      addRepresentation("surface") %>%
      stageParameters(backgroundColor = "white")
  })
}
shinyApp(ui, server)
```

  
![Screenshot 2022-08-15 at 13 15 38](https://user-images.githubusercontent.com/45127542/184625794-1c8f252c-f7a8-4e0e-8cab-41983d727432.png)

**Comment by cwbcm** [comment]
I see, thank you!

**Comment by BJWiley233** [comment]
Not sure why my background is automatically black and I cannot change it?  Must by an Rshiny thing.

![image](https://user-images.githubusercontent.com/26236052/211143054-a418ea0b-706d-4449-9a5b-f803acd41f89.png)

**Comment by BJWiley233** [comment]
Well seems Shiny hasn't caught up to some HTML5 stuff.  They do not give `id` selector attributes to canvas so you can change them all with something like.

```
                                              tags$style(HTML("
                                                      #container {
                                                        position: relative;
                                                      }
                                                      #container canvas, #overlay {
                                                        position: absolute;
                                                      }
                                                      canvas {
                                                        border: 1px solid black;
                                                      }
                                                      ")
                                      )
```

and then this works for any color I want
```R
%>%
          stageParameters(backgroundColor = "white")
```
