### ISSUE TITLE
How to make a video?

### ISSUE THREAD

**Issue by maximinio** [nvelden/NGLVieweR#8]
Hi there,
I'm currently making very beautiful NGLVieweR spinning representations displayed within the Rstudio Viewer panel.
I see I can save it as HTML but then I don't know how to convert it to a GIF or a video.
Is there any way I can save it as such directly?
Thank you in advance!
Best,
Luca

**Comment by nvelden** [comment]
I am afraid there is no easy way to do this using the API. I made my `.gif` files by simply recording my screen using [screen2gif](https://www.screentogif.com/)

**Comment by maximinio** [comment]
Is this something you think you will develop?
I would love it, of course!
Thank you!
