### ISSUE TITLE
Using PDB file as R variable for visualization

### ISSUE THREAD

**Issue by hkarakurt8742** [nvelden/NGLVieweR#9]
Hello,
Thank you for the tool. It works amazing.
Is it possible to use it to visualize a PDB files that stored as a variable (data.frame, matrix, character etc.)?
I am using ESM API to have the structure and I am writing it as a PDB file then I use it for visualization. Is it possible to use directly the request result?

My code goes like this:

`
seq <- "CKGADGAHGVNGCPGTAGAAGSVGGPGCDGGHGGNGGNGNPGCAGGVGGAGGASGGTGVGGRGGKGGSGTPKGADGAPGAP"
headers <- c('Content-Type'='application/x-www-form-urlencoded')
response <- POST('https://api.esmatlas.com/foldSequence/v1/pdb/', body = seq , headers=headers)

structure <- enc2utf8(rawToChar(response$content))
`

Is it possible to do it with NGLVieweR?
Thank you in advance

**Comment by nvelden** [comment]
You can do this by specifying the "format" in the `NGLVieweR()` function

```
library(httr)
library(NGLVieweR)

seq <- "CKGADGAHGVNGCPGTAGAAGSVGGPGCDGGHGGNGGNGNPGCAGGVGGAGGASGGTGVGGRGGKGGSGTPKGADGAPGAP"
headers <- c('Content-Type'='application/x-www-form-urlencoded')
response <- POST('https://api.esmatlas.com/foldSequence/v1/pdb/', body = seq , headers=headers)

structure <- enc2utf8(rawToChar(response$content))

NGLVieweR(structure, format="pdb") %>%
  addRepresentation("cartoon")
```

**Comment by hkarakurt8742** [comment]
> You can do this by specifying the "format" in the `NGLVieweR()` function
> 
> ```
> library(httr)
> library(NGLVieweR)
> 
> seq <- "CKGADGAHGVNGCPGTAGAAGSVGGPGCDGGHGGNGGNGNPGCAGGVGGAGGASGGTGVGGRGGKGGSGTPKGADGAPGAP"
> headers <- c('Content-Type'='application/x-www-form-urlencoded')
> response <- POST('https://api.esmatlas.com/foldSequence/v1/pdb/', body = seq , headers=headers)
> 
> structure <- enc2utf8(rawToChar(response$content))
> 
> NGLVieweR(structure, format="pdb") %>%
>   addRepresentation("cartoon")
> ```

Thank you for your answer. It worked really nice.
